# permissions for end users to view datamoverbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamoverbackup-viewer-role
rules:
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverbackups/status
  verbs:
  - get
