# permissions for end users to edit datamoverrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamoverrestore-editor-role
rules:
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverrestores/status
  verbs:
  - get
