# permissions for end users to view datamoverrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamoverrestore-viewer-role
rules:
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverrestores/status
  verbs:
  - get
