# permissions for end users to edit datamoverbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datamoverbackup-editor-role
rules:
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverbackups/status
  verbs:
  - get
