---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverbackups/finalizers
  verbs:
  - update
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverrestores/finalizers
  verbs:
  - update
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - datamoverrestores/status
  verbs:
  - get
  - patch
  - update
