# permissions for end users to view volumesnapshotbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumesnapshotbackup-viewer-role
rules:
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - volumesnapshotbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - volumesnapshotbackups/status
  verbs:
  - get
