# permissions for end users to edit volumesnapshotbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumesnapshotbackup-editor-role
rules:
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - volumesnapshotbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pvc.oadp.openshift.io
  resources:
  - volumesnapshotbackups/status
  verbs:
  - get
