# permissions for end users to view volumesnapshotmovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumesnapshotmover-viewer-role
rules:
- apiGroups:
  - datamover.oadp.openshift.io
  resources:
  - volumesnapshotmovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datamover.oadp.openshift.io
  resources:
  - volumesnapshotmovers/status
  verbs:
  - get
