# permissions for end users to view volumesnapshotrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumesnapshotrestore-viewer-role
rules:
- apiGroups:
  - datamover.oadp.openshift.io
  resources:
  - volumesnapshotrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datamover.oadp.openshift.io
  resources:
  - volumesnapshotrestores/status
  verbs:
  - get
